openapi: 3.0.0
info:
  title: chat
  version: 1.0.0
servers:
  - url: http://localhost:5001
paths:
  /chat:
    get:
      tags:
        - default
      summary: getmessagebysender
      parameters:
        - name: id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: addmessage
      requestBody:
        content: {}
      parameters:
        - name: receiver_id
          in: query
          schema:
            type: integer
          example: '1'
        - name: sender_id
          in: query
          schema:
            type: integer
          example: '1'
        - name: message
          in: query
          schema:
            type: string
          example: tivirp
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
