openapi: 3.0.0
info:
  title: user
  version: 1.0.0
servers:
  - url: http://0.0.0.0:5000
  - url: http://localhost:5000
paths:
  /user:
    get:
      tags:
        - default
      summary: getuser
      parameters:
        - name: id
          in: query
          schema:
            type: integer
          example: '5'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: adduser
      requestBody:
        content: {}
      parameters:
        - name: first_name
          in: query
          schema:
            type: string
          example: dsdassadasdas
        - name: last_name
          in: query
          schema:
            type: string
          example: sda
        - name: email
          in: query
          schema:
            type: string
          example: ddas%40sfsfs
        - name: birth_date
          in: query
          schema:
            type: string
          example: dsdasd
        - name: login
          in: query
          schema:
            type: string
          example: dsdasd
        - name: password
          in: query
          schema:
            type: string
          example: daas
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
