openapi: 3.0.0
info:
  title: wall
  version: 1.0.0
servers:
  - url: http://localhost:5002
paths:
  /getpost:
    get:
      tags:
        - default
      summary: getpost
      parameters:
        - name: id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /dopost:
    post:
      tags:
        - default
      summary: addcomments
      requestBody:
        content: {}
      parameters:
        - name: name
          in: query
          schema:
            type: integer
          example: '31231'
        - name: login
          in: query
          schema:
            type: string
          example: CoolBoy
        - name: description
          in: query
          schema:
            type: string
          example: sdasdas
        - name: data
          in: query
          schema:
            type: string
          example: dsdasdfdsfs
        - name: creation_date
          in: query
          schema:
            type: string
          example: 10.03.2022
        - name: comments
          in: query
          schema:
            type: string
          example: daas
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /checkcomments:
    get:
      tags:
        - default
      summary: getcomments
      parameters:
        - name: id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
